# 项目相关配置
fuce:
  #名称
  name: esjypt
  #版本
  version: 1.0
  #版权年份
  copyrightYear: 2019
#tomcat config
server:
  port: 8080
  ##项目名字配置
  servlet:
    context-path: /esjypt
  tomcat:
    max-threads: 128
    min-spare-threads: 5
    uri-encoding: UTF-8
    #shiro 报错修改的地方
    max-connections: 200000
    max-http-post-size: 9000000
spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapperLocations: classpath*:mapper/*.xml
  executor-type: reuse
  type-aliases-package: com.*.model
  configuration:
    map-underscore-to-camel-case: true